version: "3.7"

services:
  react:
    build: ../react/
    ports:
      - "5000:5000"
    restart: always

  nginx:
    build: ../nginx/
    depends_on:
      - react
    ports:
      - "8080:80"
    restart: always
